backend:
  name: github
  repo: mrfoster/blueberry-food-website
  branch: features/netlify-cms

media_folder: static/assets
public_folder: /assets

collections:
  - name: pages
    label: Pages
    media_folder: ''
    public_folder: ''
    files:
      - file: data/home.md
        label: Home
        delete: false
        name: home
        fields:
          - { name: path, label: Path, widget: hidden, default: / }
          - { name: body, label: Body, widget: markdown }
  - name: location
    label: Locations
    folder: data/locations
    path: '{{slug}}'
    media_folder: 
    public_folder: 
    create: true
    fields:
      - { name: slug, label: Slug }
      - { name: name, label: Name }
      - { name: image, label: Image, widget: image }
      - name: images
        label: Images
        media_library:
          config:
            multiple: true
      - label: "Manual PDF"
        name: "manual_pdf"
        widget: "file"
        media_library:
          config:
            multiple: true
      - { name: location, label: Location }
      - { name: googlePlaceId, label: Google Place Id }
      - { name: body, label: Body, widget: markdown }
